### ISSUE TITLE
atividad 11 Practica Visualización

### ISSUE THREAD

**Issue by HECTOR-KDM02** [SistemasTecTlaxiaco/actividad-11-practica-de-visualizacion-de-datos-team-ola#1]
[reporte 11.pdf](https://github.com/SistemasTecTlaxiaco/actividad-11-practica-de-visualizacion-de-datos-team-ola/files/15489934/reporte.11.pdf)

REPORTE

**Comment by josealfredo79** [comment]
Bien hecho y revisado...Calificación 18
